# (mandatory) 
# Path to coverage profile file (output of `go test -coverprofile` command).
#
# For cases where there are many coverage profiles, such as when running 
# unit tests and integration tests separately, you can combine all those
# profiles into one. In this case, the profile should have a comma-separated list 
# of profile files, e.g., 'cover_unit.out,cover_integration.out'.
profile: cover.out

# Holds coverage thresholds percentages, values should be in range [0-100].
threshold:
  # (optional; default 0) 
  # Minimum coverage percentage required for each package.
  package: 50

  # (optional; default 0) 
  # Minimum overall project coverage percentage required.
  total: 80

# Holds regexp rules which will exclude matched files or packages 
# from coverage statistics.
exclude:
  # Exclude files or packages matching their paths
  paths:
    - ^internal/ast/print.go$         # handled in integration tests
    - ^internal/gqjson/printer.go$    # handled in integration tests
    - ^cmd                            # handled in integration tests
    - ^internal/utils                 # just type definitions
    - ^internal/cmd                   # handled in integration tests
    - ^internal/stream                   # handled in integration tests

# If specified, saves the current test coverage breakdown to this file.
#
# Typically, this breakdown is generated only for main (base) branches and 
# stored as an artifact. Later, this file can be used in feature branches 
# to compare test coverage against the base branch.
breakdown-file-name: ''