name: Documentation
description: Report any mistakes or missing information from the documentation or the examples
labels: kind/documentation
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Note**: Most documentation lives and can be implemented with a small PR.

  - type: textarea
    id: rationale
    attributes:
      label: Why is this needed?
    validations:
      required: false
